baseurl = "https://pankajniroula.com.np/"
copyright = "All Permissions Granted for Reuse"
disqusshortname = "npankaj365"
languagecode = "en-EN"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Pankaj NIROULA"

[[menu.main]]
identifier = "blog"
name = "Home"
url = "/"
weight = 120
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post"
weight = 119
[[menu.main]]
identifier = "poem"
name = "Poems"
url = "/poem"
weight = 118
[[menu.main]]
name = "Github"
pre = "<h3>Find me</h3>"
url = "https://github.com/npankaj365"
weight = 100
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/npankaj365"
weight = 101
[[menu.main]]
name = "Keybase"
pre = "<h3>Contact me</h3>"
url = "https://Keybase.io/npankaj365"
weight = 109

[params]
author = "Pankaj NIROULA"
authorlocation = "Kathmandu, Nepal"
authorwebsite = "https://pankajniroula.com.np"
authorbio = "Software Engineer and Open Source Enthusiast"
cover = "img/open_sky.jpg"
description = "It is better to travel well than to arrive."
githubName = "npankaj365"
linkedinName = "npankaj365"
email = "info@pankajniroula.com.np"
googleAnalyticsUserID = "UA-128968851-1"
hideHUGOSupport = false
logo = "img/logo.png"
twitterName = "npankaj365"

[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
